### ISSUE TITLE
Add links to projectliberty discourse

### ISSUE THREAD

**Issue by dduncanmccourt** [LibertyDSNP/liberty-web#9]
Hi -
Please add links to the Project liberty forum to the site.
https://forum.projectliberty.io 

Add link to forum on
1)  Let's connect page -  include form, email and forum link
2) Add link to forum on landing page - Below intro text: If you are interested, let's connect - join our forum [link] or join our mailing list [link to let's connect]

Thanks!
Denise

**Comment by dduncanmccourt** [comment]
Hi Team -
Please add this text below the opening paragraphs on the home page

If you are interested, please join our forum

https://forum.projectliberty.io/

or join our mailing list (link to https://www.projectliberty.io/contact.html)

Thanks!
Denise

**Comment by kfogel** [comment]
Noting that it's `forums.projectliberty.io` now.  Also, I'm pretty sure this is taken care of in the new web site revamp?  "Assigning" (in the very tentative sense described [here](https://github.com/LibertyDSNP/liberty-web/issues/12#issuecomment-824115179) to @claireolmstead so she can confirm and, most likely, just close this issue.

**Comment by claireclark1** [comment]
This site has been closed in favor of a WordPress site.  There is a link to the Project Liberty forum in the footer of the new site ([https://www.projectliberty.io/](https://www.projectliberty.io/)).
